"""
Shared data models for the Pricing Intelligence Agent pipeline.

Every agent boundary in this system passes one of these Pydantic models,
never a raw string or dict. If an LLM call doesn't produce valid data
matching a schema, we catch that at the boundary where it happened,
instead of letting a malformed value silently propagate three agents
downstream and fail somewhere confusing.
"""

from __future__ import annotations
from datetime import datetime, date
from enum import Enum
from typing import Optional
from pydantic import BaseModel, Field, field_validator

import config


# ---------------------------------------------------------------------------
# Catalog (our own product data — not competitor data)
# ---------------------------------------------------------------------------

class CatalogItem(BaseModel):
    sku: str
    name: str
    brand: str
    category: str
    our_price: float = Field(gt=0)
    cost: float = Field(gt=0)
    stock: int = Field(ge=0)

    @property
    def current_margin_pct(self) -> float:
        return (self.our_price - self.cost) / self.our_price


# ---------------------------------------------------------------------------
# Competitor price data (synthetic, generated by data/mock_price_generator.py)
# ---------------------------------------------------------------------------

class CompetitorPricePoint(BaseModel):
    """One competitor's price for one SKU on one day."""
    sku: str
    competitor: str
    price: float = Field(gt=0)
    in_stock: bool
    date: date


class CompetitorPriceHistory(BaseModel):
    """A competitor's price trend for one SKU across several days."""
    sku: str
    competitor: str
    points: list[CompetitorPricePoint]

    @property
    def latest(self) -> CompetitorPricePoint:
        return max(self.points, key=lambda p: p.date)

    @property
    def trend_pct(self) -> float:
        """% change from the oldest point in history to the latest.
        Positive = competitor is raising prices, negative = cutting them."""
        if len(self.points) < 2:
            return 0.0
        sorted_points = sorted(self.points, key=lambda p: p.date)
        first, last = sorted_points[0], sorted_points[-1]
        return (last.price - first.price) / first.price


# ---------------------------------------------------------------------------
# Researcher agent output
# ---------------------------------------------------------------------------

class ResearchBatch(BaseModel):
    """Full output of one Researcher agent run: today's snapshot plus
    each SKU's recent history, ready for the Analyst agent."""
    run_id: str
    histories: list[CompetitorPriceHistory]
    skus_requested: int
    skus_found: int
    errors: list[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Analyst agent output
# ---------------------------------------------------------------------------

class GuardrailViolation(str, Enum):
    NONE = "none"
    BELOW_MIN_MARGIN = "below_min_margin"
    EXCEEDS_MAX_PRICE_CHANGE = "exceeds_max_price_change"
    LOW_STOCK_BLOCKS_RAISE = "low_stock_blocks_raise"


class SkuAnalysis(BaseModel):
    sku: str
    our_price: float
    min_competitor_price: Optional[float] = None
    max_competitor_price: Optional[float] = None
    avg_competitor_price: Optional[float] = None
    price_delta_pct: Optional[float] = Field(
        default=None,
        description="(our_price - avg_competitor_price) / our_price. "
        "Positive means we're priced above the market.",
    )
    avg_competitor_trend_pct: Optional[float] = Field(
        default=None,
        description="Average trend_pct across competitors — are they "
        "trending their prices up or down over the history window?",
    )
    current_margin_pct: float
    competitor_count: int
    needs_decision: bool = Field(
        description="True if this SKU's price gap is large enough to be "
        "worth sending to the Decision agent"
    )
    notes: str = ""


class AnalysisBatch(BaseModel):
    run_id: str
    analyses: list[SkuAnalysis]
    flagged_count: int


# ---------------------------------------------------------------------------
# Decision agent — LLM-facing schema (minimal, no gt/lt constraints)
# ---------------------------------------------------------------------------

class LLMPriceSuggestion(BaseModel):
    """What we actually ask Gemini to produce. Deliberately minimal:
    only fields the model needs to decide, using ge/le (inclusive
    bounds -> JSON schema 'minimum'/'maximum') rather than gt/lt
    (exclusive bounds -> 'exclusiveMinimum'/'exclusiveMaximum'), because
    Gemini's schema converter rejects exclusiveMinimum/exclusiveMaximum
    as an unsupported keyword. Fields like sku, current_price, and
    guardrail_violation are known to us already or computed by us
    afterward -- there's no reason to trust an LLM to echo back data
    we already have, or to compute a guardrail check itself.
    """
    recommended_price: float = Field(ge=0.01)
    confidence: float = Field(ge=0.0, le=1.0)
    reasoning: str


# ---------------------------------------------------------------------------
# Decision agent output — the full internal model, built from an
# LLMPriceSuggestion plus data decision.py already has
# ---------------------------------------------------------------------------

class PriceRecommendation(BaseModel):
    sku: str
    current_price: float
    recommended_price: float = Field(gt=0)
    confidence: float = Field(ge=0.0, le=1.0)
    reasoning: str
    projected_margin_pct: float
    reversible: bool = Field(
        default=True,
        description="Price cuts are reversible; large raises are treated "
        "as not reversible, which forces human review regardless of confidence.",
    )
    guardrail_violation: GuardrailViolation = GuardrailViolation.NONE

    @field_validator("recommended_price")
    @classmethod
    def sane_change(cls, v, info):
        current = info.data.get("current_price")
        if current and abs(v - current) / current > config.MAX_PRICE_CHANGE_PCT:
            raise ValueError(
                f"Recommended price change exceeds MAX_PRICE_CHANGE_PCT "
                f"({config.MAX_PRICE_CHANGE_PCT:.0%}) — likely a bad LLM output"
            )
        return v


class DecisionBatch(BaseModel):
    run_id: str
    recommendations: list[PriceRecommendation]


# ---------------------------------------------------------------------------
# Approval / execution
# ---------------------------------------------------------------------------

class ApprovalOutcome(str, Enum):
    AUTO_APPROVED = "auto_approved"
    HUMAN_APPROVED = "human_approved"
    HUMAN_REJECTED = "human_rejected"
    TIMED_OUT = "timed_out"


class ExecutionResult(BaseModel):
    sku: str
    outcome: ApprovalOutcome
    old_price: float
    new_price: float
    executed: bool
    timestamp: datetime = Field(default_factory=datetime.utcnow)